spring:
  datasource:
    url: jdbc:mysql://beep-database.c96ms6m44sen.ap-northeast-2.rds.amazonaws.com:3306/beepDatabase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: beep_user
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
  data:
    redis:
      mail:
        host: beep-redis # ?? ???? ???? ???? ?? ??
        port: 6379

  batch:
    jdbc:
      initialize-schema: always

  mail:
    username: heunseo9@gmail.com
    password: cyje eoaq uxsv upst
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000 # SMTP ??? ??? ???? ??? ???? ?? ??? 50,000ms
        smtp.starttls.enable: true

application:
  jwt:
    refresh-exp: 2592000000 #30일 // 나중에 3일로 바꾸기
#    refresh-exp: 60000 # 1분
    access-exp: 86400000 # 24시간
#    access-exp: 30000 # 24시간
    prefix: Bearer
    header: Authorization
    secretKey: 17e837880e3be483ceb38282686c6e274c9eda3ea4ecdb62f05f93ac8bc70e5a

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
