name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ] # 해당 branch에 푸쉬 발생 시 업데이트
  pull_request:
    branches: [ "main" ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: set chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/beep:0.0.1-SNAPSHOT .
          docker push ${{ secrets.DOCKER_USERNAME }}/beep:0.0.1-SNAPSHOT

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # EC2 private key
          envs: GITHUB_SHA
          port: 22
          script: |
            docker stop beep
            docker stop beep-redis
            docker rm beep
            docker rm beep-redis
            docker rmi ${{ secrets.DOCKER_USERNAME }}/beep:0.0.1-SNAPSHOT
            docker pull ${{ secrets.DOCKER_USERNAME }}/beep:0.0.1-SNAPSHOT
            
            docker run -d --name beep-redis --network redis-network redis
            docker run -d -p 80:8080 --name beep --network redis-network \
              --env SPRING_REDIS_HOST=beep-redis --env SPRING_REDIS_PORT=6379 ${{ secrets.DOCKER_USERNAME }}/beep:0.0.1-SNAPSHOT
            

